"""add_addressbook_tables_contacts_departments_groups

Revision ID: d046dec9949e
Revises: 694ac3535013
Create Date: 2025-10-28 16:43:00.726120+09:00

SkyBoot Mail SaaS 마이그레이션 스크립트
- 다중 조직 지원
- 데이터 격리 보장
- 백업 및 복원 지원
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd046dec9949e'
down_revision = '694ac3535013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    마이그레이션 업그레이드 실행
    
    이 함수는 데이터베이스 스키마를 새 버전으로 업그레이드합니다.
    SaaS 환경에서 조직별 데이터 격리를 유지하면서 안전하게 실행됩니다.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='unique_org_department_name')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_org_id'), ['org_id'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='unique_org_group_name')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_org_id'), ['org_id'], unique=False)

    op.create_table('contacts',
    sa.Column('contact_uuid', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('contact_uuid'),
    sa.UniqueConstraint('org_id', 'email', name='unique_org_contact_email')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_contact_uuid'), ['contact_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_org_id'), ['org_id'], unique=False)

    op.create_table('contact_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('contact_uuid', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contact_uuid'], ['contacts.contact_uuid'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'contact_uuid', 'group_id', name='unique_org_contact_group')
    )
    with op.batch_alter_table('contact_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_groups_contact_uuid'), ['contact_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_groups_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_groups_org_id'), ['org_id'], unique=False)

    op.drop_table('login_logs_backup')
    op.drop_table('virtual_aliases')
    op.drop_table('virtual_domains')
    op.drop_table('virtual_users')
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='로그인 시도 사용자 ID')

    with op.batch_alter_table('mail_folders', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'mail_users', ['user_uuid'], ['user_uuid'])
        batch_op.create_foreign_key(None, 'mail_folders', ['parent_id'], ['id'])
        batch_op.create_foreign_key(None, 'organizations', ['org_id'], ['org_id'])

    with op.batch_alter_table('mail_in_folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True, comment='읽음 상태'))
        batch_op.add_column(sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='읽은 시간'))

    with op.batch_alter_table('mail_logs', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               existing_comment='조직 ID')

    with op.batch_alter_table('mail_users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'organizations', ['org_id'], ['org_id'])

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_uuid'], ['user_uuid'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_2fa_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True,
               existing_comment='2FA 활성화 여부')
        batch_op.alter_column('totp_secret',
               existing_type=sa.VARCHAR(length=32),
               comment='TOTP 시크릿 키',
               existing_comment='TOTP 시크릿 키 (암호화됨)',
               existing_nullable=True)
        batch_op.alter_column('backup_codes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               comment='백업 코드 JSON',
               existing_comment='백업 코드 목록 (암호화됨)',
               existing_nullable=True)
        batch_op.drop_index('idx_users_2fa_enabled')
        batch_op.drop_index('idx_users_last_2fa_at')
        batch_op.drop_constraint('users_unique_key', type_='unique')
        batch_op.create_foreign_key(None, 'organizations', ['org_id'], ['org_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """
    마이그레이션 다운그레이드 실행
    
    이 함수는 데이터베이스 스키마를 이전 버전으로 되돌립니다.
    데이터 손실을 방지하기 위해 신중하게 구현되어야 합니다.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('users_unique_key', ['org_id', 'user_id'])
        batch_op.create_index('idx_users_last_2fa_at', ['last_2fa_at'], unique=False)
        batch_op.create_index('idx_users_2fa_enabled', ['is_2fa_enabled'], unique=False)
        batch_op.alter_column('backup_codes',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment='백업 코드 목록 (암호화됨)',
               existing_comment='백업 코드 JSON',
               existing_nullable=True)
        batch_op.alter_column('totp_secret',
               existing_type=sa.VARCHAR(length=32),
               comment='TOTP 시크릿 키 (암호화됨)',
               existing_comment='TOTP 시크릿 키',
               existing_nullable=True)
        batch_op.alter_column('is_2fa_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False,
               existing_comment='2FA 활성화 여부')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('mail_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('mail_logs', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               existing_comment='조직 ID')

    with op.batch_alter_table('mail_in_folders', schema=None) as batch_op:
        batch_op.drop_column('read_at')
        batch_op.drop_column('is_read')

    with op.batch_alter_table('mail_folders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='로그인 시도 사용자 ID')

    op.create_table('virtual_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['virtual_domains.id'], name='virtual_users_domain_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='virtual_users_pkey'),
    sa.UniqueConstraint('email', name='virtual_users_email_key')
    )
    op.create_table('virtual_domains',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('virtual_domains_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='virtual_domains_pkey'),
    sa.UniqueConstraint('name', name='virtual_domains_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('virtual_aliases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['virtual_domains.id'], name='virtual_aliases_domain_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='virtual_aliases_pkey')
    )
    op.create_table('login_logs_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_uuid', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('login_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('failure_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    with op.batch_alter_table('contact_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_groups_org_id'))
        batch_op.drop_index(batch_op.f('ix_contact_groups_id'))
        batch_op.drop_index(batch_op.f('ix_contact_groups_group_id'))
        batch_op.drop_index(batch_op.f('ix_contact_groups_contact_uuid'))

    op.drop_table('contact_groups')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_org_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_contacts_contact_uuid'))

    op.drop_table('contacts')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_org_id'))
        batch_op.drop_index(batch_op.f('ix_groups_id'))

    op.drop_table('groups')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_org_id'))
        batch_op.drop_index(batch_op.f('ix_departments_id'))

    op.drop_table('departments')
    # ### end Alembic commands ###


def validate_saas_constraints() -> None:
    """
    SaaS 제약 조건 검증
    
    마이그레이션 후 다음 사항을 확인합니다:
    - 조직별 데이터 격리 유지
    - 외래 키 제약 조건 유효성
    - 인덱스 성능 최적화
    """
    # 구현 필요시 여기에 검증 로직 추가
    pass


def backup_critical_data() -> None:
    """
    중요 데이터 백업
    
    마이그레이션 전 중요한 데이터를 백업합니다.
    조직별로 분리된 백업을 생성하여 데이터 격리를 유지합니다.
    """
    # 구현 필요시 여기에 백업 로직 추가
    pass